version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      development:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"

  # Web app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      next-ecosystem:
        patterns:
          - "next"
          - "@next/*"
          - "react"
          - "react-dom"
      ui-libraries:
        patterns:
          - "@radix-ui/*"
          - "tailwind*"
          - "class-variance-authority"
          - "clsx"

  # Mobile app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      expo-ecosystem:
        patterns:
          - "expo*"
          - "react-native*"
      
  # Shared package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"