[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

# 本番環境設定
[context.production]
  environment = { NODE_ENV = "production" }

# プレビュー環境設定（PRなど）
[context.deploy-preview]
  environment = { NODE_ENV = "production" }

# ブランチデプロイ設定
[context.branch-deploy]
  environment = { NODE_ENV = "production" }

# リダイレクト設定（SPA用）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Netlify Functions設定
[functions]
  directory = "netlify/functions" 