name: Nightly CI

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日深夜に実行
  workflow_dispatch:      # 手動実行も可能

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/k6-action@v0.2.0

      - name: Run load test
        run: k6 run tests/load/reservation-flow.js
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Upload k6 report
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: k6-report.html

  security-scan:
    needs: load-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ secrets.NEXT_PUBLIC_API_URL }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html

  notify:
    needs: [load-test, security-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        continue-on-error: true 