name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      # クリーンインストール
      - name: Clean npm cache
        run: npm cache clean --force
      - name: Remove node_modules
        run: rm -rf node_modules
      - name: Install dependencies with exact versions
        run: npm ci --legacy-peer-deps
      - name: Verify testing dependencies
        run: |
          npm list vitest @testing-library/react @testing-library/jest-dom --depth=0 || true
      - name: Clear Playwright Cache
        run: rm -rf ~/.cache/ms-playwright
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Check for missing dependencies
        run: npm ls || true
      - name: Run unit tests
        run: npm run test:unit
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          if-no-files-found: ignore
      - name: Upload npm debug logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-logs
          path: npm-debug.log
          if-no-files-found: ignore
  
  # E2Eテスト実行ジョブ
  e2e-test:
    runs-on: ubuntu-latest
    needs: test  # 単体テスト完了後に実行
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Clear Playwright Cache
        run: rm -rf ~/.cache/ms-playwright
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        env:
          CI: true
          E2E_BASE_URL: http://localhost:5173
        # フロントエンドサーバーを起動してテスト実行
        run: |
          # フロントエンドサーバーを起動
          npm run dev &
          # サーバーの起動を待つ
          npx wait-on http://localhost:5173
          # E2Eテストを実行（ChromiumのみでOK）
          npx playwright test tests/e2e --project=chromium
      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore
  
  # AI サービス用のテスト（後で有効化予定）
  # test-python:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'
  #     - name: Install dependencies
  #       run: |
  #         cd apps/ai-service
  #         pip install -r requirements-dev.txt
  #     - name: Run tests
  #       run: |
  #         cd apps/ai-service
  #         pytest --cov 