name: Deploy All Apps

on:
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.filter.outputs.web }}
      mobile: ${{ steps.filter.outputs.mobile }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            web:
              - 'apps/web/**'
              - 'packages/shared/**'
              - 'prisma/**'
              - 'package-lock.json'
              - 'turbo.json'
            mobile:
              - 'apps/mobile/**'
              - 'packages/shared/**'
              - 'package-lock.json'
              - 'turbo.json'

  deploy-web:
    needs: detect-changes
    if: needs.detect-changes.outputs.web == 'true'
    uses: ./.github/workflows/deploy-web.yml
    secrets: inherit

  deploy-mobile:
    needs: detect-changes
    if: needs.detect-changes.outputs.mobile == 'true'
    uses: ./.github/workflows/deploy-mobile.yml
    secrets: inherit