name: Mobile App Preview

on:
  pull_request:
    paths:
      - 'apps/mobile/**'
      - 'packages/shared/**'
  workflow_dispatch:

jobs:
  build-preview:
    name: Build Expo Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build --workspace=@mued/shared

      - name: Create preview build
        run: |
          cd apps/mobile
          eas build --profile preview --platform all --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Comment PR with build links
        uses: actions/github-script@v7
        with:
          script: |
            const output = `
            📱 **Mobile Preview Build Ready**
            
            - iOS: [Install on TestFlight](#)
            - Android: [Download APK](#)
            
            Build will expire in 30 days.
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })