name: PWA Build Check (Vercel handles deployment)
on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/pwa.yml'
      - 'packages/shared/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Build shared package
        run: npm run build:shared
        
      - name: Build PWA
        run: npm run build:mobile:web
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}
          EXPO_PUBLIC_VAPID_PUBLIC_KEY: ${{ secrets.EXPO_PUBLIC_VAPID_PUBLIC_KEY }}
      
      - name: List dist contents
        run: |
          echo "Listing dist directory contents:"
          ls -la apps/mobile/dist/
          
      # Vercel GitHub連携でデプロイされるため、ここでは成功確認のみ
      - name: Build Success
        run: |
          echo "✅ PWA build completed successfully!"
          echo "Vercel will automatically deploy this via GitHub integration"