name: Shared Package CI

on:
  push:
    paths:
      - 'packages/shared/**'
      - '.github/workflows/shared-package.yml'
  pull_request:
    paths:
      - 'packages/shared/**'

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint shared package
        run: npm run lint --workspace=@mued/shared

      - name: Type check
        run: npm run typecheck --workspace=@mued/shared

      - name: Build package
        run: npm run build --workspace=@mued/shared

      - name: Test package
        run: npm run test --workspace=@mued/shared

  compatibility:
    name: Compatibility Check
    runs-on: ubuntu-latest
    needs: [quality]
    strategy:
      matrix:
        node: ['18', '20']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Node ${{ matrix.node }}
        run: npm run build --workspace=@mued/shared

  publish-preview:
    name: Publish Preview Package
    runs-on: ubuntu-latest
    needs: [compatibility]
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build --workspace=@mued/shared

      - name: Version preview package
        run: |
          cd packages/shared
          npm version prerelease --preid=pr.${{ github.event.pull_request.number }}

      - name: Publish to GitHub Packages
        run: |
          cd packages/shared
          npm publish --tag preview
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}