name: Supabase DB Sync

on:
  push:
    branches: [ main ]
    paths:
      - "supabase/migrations/**"
      - ".github/workflows/supabase-sync.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node (for pnpm & Supabase CLI)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install project dependencies (lightweight)
        run: pnpm install --frozen-lockfile --filter supabase... --ignore-scripts

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        run: supabase link --project-ref $NEXT_PUBLIC_SUPABASE_URL --debug

      - name: Push migrations to Supabase
        run: supabase db push --linked --debug

      - name: Output migration history
        run: supabase db history --debug 